export const icons = {
  search: '🔍',
  profile: '💼',
  ad: '📢',
  contacts: '👥',
  gender: '⚤',
  photo: '📷',
  birthday: '📅',
  info: '📜',
  error: '⛔',
  warning: '⚠',
  success: '👌',
  hello: '👋',
  home: '',
  woman: '🚺',
  man: '🚹',
  fire: '🔥',
  congrat: '🎉',
  house: '🏠',
  location: '🌎'
};