import Context from "telegraf";
export const getMessage = ctx => ctx.update?.message;
export const getCallbackQuery = ctx => ctx.update?.callback_query;
export const getMessageText = ctx => getMessage(ctx)?.text;
export const getMessageSender = ctx => getMessage(ctx)?.from || getCallbackQuery(ctx)?.from;
export const getMessageSenderId = ctx => getMessageSender(ctx)?.id;
export const getMessageChat = ctx => getMessage(ctx)?.chat;
export const getAction = ctx => ctx.update?.callback_query?.data;
export const getUserId = ctx => getMessage(ctx)?.from?.id || getCallbackQuery(ctx)?.from?.id;
export const getPhoto = ctx => getMessage(ctx)?.photo;